# file: .github/workflows/initial_steps.yml
name: initial_steps
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  initial: # имя задания
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      # Ставим зависимости
      - run: make setup
      # Запускаем линтер
      - run: make lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name
      # выводит строку Hello from Hexlet!
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
